### PR TITLE
Color type format toggle

### PR DESCRIPTION
**Pull request by dubert**
Solves https://github.com/thomaslindstrom/color-picker/issues/3

Preview:
 
screen shot 2015-04-20 at 19 23 30

### CODE REVIEW

**Comment by thomaslindstrom** [comment]
Excellent work. I quickly pulled and tested this, and it works well. I'm going to review the code and the design and get back to you. This'll make a lot of people happy, for sure!

**Comment by dubert** [comment]
Thanks @thomaslindstrom!

One small thing I noticed:
When opening the color picker on a hex, and the user toggles the 'hex' type, the color gets its value from `SaturationSelector.getColorAtPosition _saturation.x, _saturation.y` instead of the hex directly. 

I didn't want to rewrite too much too accommodate this. What are your thoughts on the best way to address it?

Preview of what I mean: screen shot 2015-04-20 at 23 13 57

**Comment by dubert** [comment]
Quick note about the design:

I struggled with how to best fit the toggle in with the aesthetic of the color-picker since it is so clean and elegant on its own. So I would definitely appreciate your review/opinion of the design specifically and I'll implement those accordingly, unless you want to handle it yourself.

**Comment by thomaslindstrom** [comment]
I've been churning how to do this in my head for a couple of months, and I think I already have settled on how I'd like it done. Instead of trying to explain it using words, I'll just implement it and ask you what you think about it!

I'm starting on this right now.

Regarding the issue on the value changing to something else than the input when you change the formatting: I think, if I'm not mistaken, I've countered this problem previously. I'll look into this too.

**Comment by dubert** [comment]
Terrific. Anything I can help regarding it?

**Comment by thomaslindstrom** [comment]
Sorry for not responding, @dubert. When looking around, verifying your pull request, I realised the `color-picker` is one year old and looks the part. I played with a couple ideas on what to do, and eventually settled on rewriting everything from scratch. 

It should be done by now, and is ready for testing. If you'd like, I'd love for you to take a look at it before I push it out. I feel bad for making you do all this work and then none of it got through – but there's tons of `TODO` comments in `v2.0.0`, if you still feel like contributing. 

Again, sorry – if it makes you feel better, it was you who pushed me into doing this, and for that I am glad and thankful!

https://github.com/thomaslindstrom/color-picker/tree/v2.0.0

**Pull request closed without merging**
