### PR TITLE
Export a color picker service

### LINKED ISSUE #156: Exposing a service for third party packages
It would be great if the package could provide a service to allow packages to open a color picker with a specific color, a screen position and a function to callback when the user is done with the picker (by passing either the new color or undefined if cancelled, or something along this line).

Related to abe33/atom-pigments#16

### PR DESCRIPTION
**Pull request by steelbrain**
Fixes #156

cc @abe33

[Review on Reviewable](https://reviewable.io/reviews/thomaslindstrom/color-picker/163)

### CODE REVIEW

**Comment by thomaslindstrom** [comment]
Amazing, @steelbrain! Thanks!

**Comment by steelbrain** [comment]
@thomaslindstrom Can we please get a release with this?

**Comment by thomaslindstrom** [comment]
Coming up in a few minutes.

**Comment by thomaslindstrom** [comment]
There we go, @steelbrain. `2.1.0` is out.

**Comment by steelbrain** [comment]
Thanks @thomaslindstrom :rose:

**Comment by abe33** [comment]
Thanks guys :+1:, I'll take a look at that this week-end

**Comment by abe33** [comment]
So I implemented a basic support in abe33/atom-pigments#16, but sadly it still lacking the ability to specify the initial color for the new picker so it gives some weird results when the picker doesn't know how to parse a color (it's like it pick a color at random each it opens). Maybe this should be taken care of as part of your effort to move to ES6?

**Pull request merged**
